#!/bin/bash

command="$1"
case "${command}" in
  generate_nuget_config)
      cat << EOF > ~/.nuget/NuGet/NuGet.Config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nancy-myget" value="https://www.myget.org/F/nancyfx/api/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <repositoryPath>$PWD/nuget-packages</repositoryPath>
  </config>
</configuration>
EOF
      exit $?
      ;;
  build)
  # add:
  # <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  # to ~/.nuget/.../NuGet.config
      dotnet build --configuration=Release
      exit $?
      ;;
  utest)
      dotnet test
      exit $?
      ;;
  itest)
      bats tests/integration/bats
      exit $?
      ;;
  run)
      dotnet run --project=./src/BranchOfficeBackend/
      exit $?
      ;;
  generate_hq_api_client)
      # this generates HQ API client in C#, but the code is very long and complicated
      dojo -c Dojofile.swagger "nswag run /runtime:NetCore20"
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
